name: "mvn-release"
description: "Generate mvn release"
inputs:
  github_token:
    description: "Github token" 
    required: true
runs:
  using: "composite"
  steps:
  - name: Remove snapshot
    shell: bash
    run: |
      mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
  - name: Release version
    uses: EndBug/add-and-commit@v7
    with:
      message: Release version   
  - name: Merge main -> develop
    uses: devmasx/merge-branch@1.4.0
    with:
      type: now
      from_branch: main
      target_branch: develop
      github_token: ${{ inputs.github_token }}         
  
