name: "mvn-release"
description: "Generate mvn release"
inputs:
  github_token:
    description: "Github token" 
    required: true
runs:
  using: "composite"
  steps:
  - name: Remove snapshot
    shell: bash
    run: |
      mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
  - name: Release version
    uses: EndBug/add-and-commit@v9
    with:
      message: Release version   
      author_name: github-actions
      author_email: action@github.com


  # - name:  Merge main into develop      
  #   uses: tukasz/direct-merge-action@master
  #   with:
  #     GITHUB_TOKEN: ${{ inputs.github_token }} 
  #     source-branch: main
  #     target-branch: develop
  #     commit-message: "New snapshot version"
  # - name: Up Merge
  #   uses: bambamboole/gha-upmerge@v1.0.1
  #   with:
  #     from_branch: 'main'
  #     to_branch: 'develop'
  #     user_name: github-actions
  #     user_email: action@github.com
  #   env:
  #     GITHUB_TOKEN: ${{ inputs.github_token }}     
  # - name: Merge main -> develop
  #   uses: devmasx/merge-branch@1.4.0
  #   with:
  #     type: now
  #     from_branch: main
  #     target_branch: develop
  #     github_token: ${{ inputs.github_token }}         

  
